eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://discovery-service:8761/eureka}
management.endpoints.web.exposure.include=*


spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


auth.service.jwks.url=http://auth-service:8081/api/v1/auth/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:8081/api/v1/auth/.well-known/jwks.json