server.port=8087


spring.datasource.url=jdbc:h2:mem:content-service
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true



minio.server.url=http://minio:9000
minio.access-key=admin
minio.secret-key=admin12345
minio.course.video.bucket.name=course-videos



spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2MB


logging.level.com.saas.mohammed=DEBUG
logging.level.io.minio=INFO

upload.max-concurrent-uploads=3