server.port=8761


# ADD THESE LINES
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka



# Static Resource Configuration
spring.mvc.static-path-pattern=/eureka/**
spring.web.resources.static-locations=classpath:/static/eureka/,classpath:/META-INF/resources/eureka/

# Optional: Disable security if you're having authentication issues
management.security.enabled=false