server.port=8083

spring.datasource.url=jdbc:h2:mem:email-service
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


spring.kafka.consumer.group-id=email-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.saas.mohammed.common.dtos



spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
#spring.mail.username=8b88aa001@smtp-brevo.com
#spring.mail.password=BWP8tjnz9qD5yU2F

spring.mail.username=godblessmetheo@gmail.com
spring.mail.password=tpgz saib qeye epyj


email.sender=simohammedalaoui1@gmail.com
email.address=30010,Fez
email.signup.confirmation.subjet=Confirm your registration