server.port=8082
spring.datasource.url=jdbc:h2:mem:user-service
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://discovery-service:8761/eureka/}
management.endpoints.web.exposure.include=*
#eureka.instance.prefer-ip-address=true
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false